steps:
  - label: ":hammer: Build personal-server-filesystem"
    commands:
      - echo "Starting build..."
      - pwd
      - ls -la
      - python --version || true
      - node --version || true
      - echo "Build complete."
    agents:
      queue: "windows"