#steps:
#  - label: ":hammer: Build personal-server-filesystem"
#    commands:
#      - echo "Starting build..."
#      - pwd
#      - ls -la
#      - python --version || true
#      - node --version || true
#      - echo "Build complete."
#    agents:
#      queue: "default-self-hosted"


steps:
  - label: ":hammer: Full Build"
    commands:
      - mkdir -p env
      - cp -R /home/dfrey/devel/ai-projects/personal-server-filesystem/env/* env/
      - echo "Stopping containers..."
      - make stop
      - echo "Cleaning Docker images..."
      - make clean-force
      - echo "Nuking Docker images..."
      - make nuke-force
      - echo "Rebuilding and starting containers..."
      - make daemon
      - echo "Containers status:"
      - make status
    agents:
      queue: "default-self-hosted"
